import "@repo/ui/styles.css"
import "./globals.css"
import type { Metadata } from "next"
import { Geist } from "next/font/google"
import Provider from "./provider"

const geist = Geist({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={geist.className} lang="en" suppressHydrationWarning>
      <body className="flex min-h-screen flex-col">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
