import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { GeistSans as Geist } from "geist/font/sans"

import "./globals.css"

import localFont from "next/font/local"

import Provider from "@/components/provider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

const Mona = localFont({
  src: "../public/fonts/mona-sans/woff2/MonaSansVariable.woff2",
  variable: "--font-mona",
  display: "swap",
})

const Gambarino = localFont({
  src: "../public/fonts/Gambarino/Gambarino-Regular.woff2",
  variable: "--font-gambarino",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Next Playground",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${Geist.className} ${Geist.variable} ${Mona.variable} ${inter.variable} ${Gambarino.variable}`}
    >
      <body className="dark">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
