import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { GeistSans as Geist } from "geist/font/sans"

import "./globals.css"

import localFont from "next/font/local"

import Provider from "@/components/provider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

const Mona = localFont({
  src: "../public/fonts/mona-sans/woff2/MonaSansVariable.woff2",
  variable: "--font-mona",
  display: "swap",
})

const Gambarino = localFont({
  src: "../public/fonts/Gambarino/Gambarino-Regular.woff2",
  variable: "--font-gambarino",
  display: "swap",
})

const Red = localFont({
  src: "../public/fonts/redaction/Redaction-Regular.woff2",
  variable: "--font-red",
  display: "swap",
})

const RedI = localFont({
  src: "../public/fonts/redaction/Redaction-Italic.woff2",
  variable: "--font-redI",
  display: "swap",
})

const Red10 = localFont({
  src: "../public/fonts/redaction/Redaction_10-Regular.woff2",
  variable: "--font-red10",
  display: "swap",
})

const Red20 = localFont({
  src: "../public/fonts/redaction/Redaction_20-Regular.woff2",
  variable: "--font-red20",
  display: "swap",
})

const Red10I = localFont({
  src: "../public/fonts/redaction/Redaction_10-Italic.woff2",
  variable: "--font-red10I",
  display: "swap",
})

const Red20I = localFont({
  src: "../public/fonts/redaction/Redaction_20-Italic.woff2",
  variable: "--font-red20I",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Next Playground",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${Geist.className} ${Geist.variable} ${Mona.variable} ${inter.variable} ${Gambarino.variable}
                  ${Red.variable} ${RedI.variable} ${Red10.variable} ${Red10I.variable} ${Red20.variable} ${Red20I.variable}`}
    >
      <body className="dark">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
